# Config of travis-ci

# using Ubuntu trusty with rootless
dist: trusty
sudo: false

services:
  # using docker
  - docker

# the envs of the setting
env:
  - GHC_VER=8.0.2  THREADED=true LLVM=3.7 DEBUG=true DOCKER=true
  - GHC_VER=8.0.2  THREADED=true          DEBUG=true
  - GHC_VER=7.10.3 THREADED=true LLVM=3.5 DEBUG=true
  - GHC_VER=7.10.3 THREADED=true          DEBUG=true
  
addons:
  apt:
    source: hvr-ghc
  packages:
    - wget
    - curl

# pre-install
before_install: source $TRAVIS_BUILD_DIR/integration/travis-ci/before.sh

# build
script:         source $TRAVIS_BUILD_DIR/integration/travis-ci/main.sh

# after success
after_success:  source $TRAVIS_BUILD_DIR/integration/travis-ci/after.sh